// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.DAL;

namespace Restaurant.DAL.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("IngredientProduct", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("IngredientsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("IngredientProduct");

                    b.HasData(
                        new
                        {
                            IngredientsId = 1,
                            ProductsId = 1
                        },
                        new
                        {
                            IngredientsId = 2,
                            ProductsId = 1
                        },
                        new
                        {
                            IngredientsId = 3,
                            ProductsId = 1
                        },
                        new
                        {
                            IngredientsId = 4,
                            ProductsId = 1
                        },
                        new
                        {
                            IngredientsId = 5,
                            ProductsId = 1
                        },
                        new
                        {
                            IngredientsId = 1,
                            ProductsId = 2
                        },
                        new
                        {
                            IngredientsId = 2,
                            ProductsId = 2
                        },
                        new
                        {
                            IngredientsId = 6,
                            ProductsId = 2
                        },
                        new
                        {
                            IngredientsId = 7,
                            ProductsId = 2
                        },
                        new
                        {
                            IngredientsId = 8,
                            ProductsId = 2
                        },
                        new
                        {
                            IngredientsId = 9,
                            ProductsId = 2
                        },
                        new
                        {
                            IngredientsId = 10,
                            ProductsId = 3
                        },
                        new
                        {
                            IngredientsId = 11,
                            ProductsId = 3
                        },
                        new
                        {
                            IngredientsId = 12,
                            ProductsId = 3
                        },
                        new
                        {
                            IngredientsId = 13,
                            ProductsId = 3
                        },
                        new
                        {
                            IngredientsId = 2,
                            ProductsId = 3
                        },
                        new
                        {
                            IngredientsId = 3,
                            ProductsId = 4
                        },
                        new
                        {
                            IngredientsId = 2,
                            ProductsId = 4
                        },
                        new
                        {
                            IngredientsId = 1,
                            ProductsId = 4
                        },
                        new
                        {
                            IngredientsId = 15,
                            ProductsId = 5
                        },
                        new
                        {
                            IngredientsId = 16,
                            ProductsId = 5
                        },
                        new
                        {
                            IngredientsId = 17,
                            ProductsId = 5
                        },
                        new
                        {
                            IngredientsId = 3,
                            ProductsId = 5
                        },
                        new
                        {
                            IngredientsId = 2,
                            ProductsId = 5
                        },
                        new
                        {
                            IngredientsId = 18,
                            ProductsId = 6
                        },
                        new
                        {
                            IngredientsId = 19,
                            ProductsId = 6
                        },
                        new
                        {
                            IngredientsId = 20,
                            ProductsId = 6
                        },
                        new
                        {
                            IngredientsId = 2,
                            ProductsId = 6
                        },
                        new
                        {
                            IngredientsId = 21,
                            ProductsId = 7
                        },
                        new
                        {
                            IngredientsId = 22,
                            ProductsId = 7
                        },
                        new
                        {
                            IngredientsId = 17,
                            ProductsId = 7
                        },
                        new
                        {
                            IngredientsId = 16,
                            ProductsId = 7
                        },
                        new
                        {
                            IngredientsId = 4,
                            ProductsId = 7
                        },
                        new
                        {
                            IngredientsId = 15,
                            ProductsId = 7
                        },
                        new
                        {
                            IngredientsId = 3,
                            ProductsId = 7
                        },
                        new
                        {
                            IngredientsId = 2,
                            ProductsId = 7
                        },
                        new
                        {
                            IngredientsId = 20,
                            ProductsId = 7
                        },
                        new
                        {
                            IngredientsId = 2,
                            ProductsId = 8
                        },
                        new
                        {
                            IngredientsId = 18,
                            ProductsId = 8
                        },
                        new
                        {
                            IngredientsId = 23,
                            ProductsId = 8
                        },
                        new
                        {
                            IngredientsId = 12,
                            ProductsId = 8
                        },
                        new
                        {
                            IngredientsId = 26,
                            ProductsId = 8
                        },
                        new
                        {
                            IngredientsId = 24,
                            ProductsId = 8
                        },
                        new
                        {
                            IngredientsId = 25,
                            ProductsId = 8
                        },
                        new
                        {
                            IngredientsId = 27,
                            ProductsId = 9
                        },
                        new
                        {
                            IngredientsId = 28,
                            ProductsId = 9
                        },
                        new
                        {
                            IngredientsId = 29,
                            ProductsId = 9
                        },
                        new
                        {
                            IngredientsId = 30,
                            ProductsId = 9
                        },
                        new
                        {
                            IngredientsId = 31,
                            ProductsId = 9
                        },
                        new
                        {
                            IngredientsId = 32,
                            ProductsId = 9
                        },
                        new
                        {
                            IngredientsId = 27,
                            ProductsId = 10
                        },
                        new
                        {
                            IngredientsId = 28,
                            ProductsId = 10
                        },
                        new
                        {
                            IngredientsId = 33,
                            ProductsId = 10
                        },
                        new
                        {
                            IngredientsId = 34,
                            ProductsId = 10
                        },
                        new
                        {
                            IngredientsId = 35,
                            ProductsId = 10
                        },
                        new
                        {
                            IngredientsId = 36,
                            ProductsId = 10
                        },
                        new
                        {
                            IngredientsId = 27,
                            ProductsId = 11
                        },
                        new
                        {
                            IngredientsId = 28,
                            ProductsId = 11
                        },
                        new
                        {
                            IngredientsId = 37,
                            ProductsId = 11
                        },
                        new
                        {
                            IngredientsId = 38,
                            ProductsId = 11
                        },
                        new
                        {
                            IngredientsId = 39,
                            ProductsId = 11
                        },
                        new
                        {
                            IngredientsId = 27,
                            ProductsId = 12
                        },
                        new
                        {
                            IngredientsId = 28,
                            ProductsId = 12
                        },
                        new
                        {
                            IngredientsId = 37,
                            ProductsId = 12
                        },
                        new
                        {
                            IngredientsId = 33,
                            ProductsId = 12
                        },
                        new
                        {
                            IngredientsId = 39,
                            ProductsId = 12
                        },
                        new
                        {
                            IngredientsId = 31,
                            ProductsId = 12
                        },
                        new
                        {
                            IngredientsId = 27,
                            ProductsId = 13
                        },
                        new
                        {
                            IngredientsId = 28,
                            ProductsId = 13
                        },
                        new
                        {
                            IngredientsId = 30,
                            ProductsId = 13
                        },
                        new
                        {
                            IngredientsId = 40,
                            ProductsId = 13
                        },
                        new
                        {
                            IngredientsId = 41,
                            ProductsId = 13
                        },
                        new
                        {
                            IngredientsId = 42,
                            ProductsId = 13
                        },
                        new
                        {
                            IngredientsId = 25,
                            ProductsId = 13
                        },
                        new
                        {
                            IngredientsId = 27,
                            ProductsId = 14
                        },
                        new
                        {
                            IngredientsId = 28,
                            ProductsId = 14
                        },
                        new
                        {
                            IngredientsId = 39,
                            ProductsId = 14
                        },
                        new
                        {
                            IngredientsId = 31,
                            ProductsId = 14
                        },
                        new
                        {
                            IngredientsId = 33,
                            ProductsId = 14
                        },
                        new
                        {
                            IngredientsId = 43,
                            ProductsId = 14
                        },
                        new
                        {
                            IngredientsId = 44,
                            ProductsId = 14
                        },
                        new
                        {
                            IngredientsId = 27,
                            ProductsId = 15
                        },
                        new
                        {
                            IngredientsId = 30,
                            ProductsId = 15
                        },
                        new
                        {
                            IngredientsId = 13,
                            ProductsId = 15
                        },
                        new
                        {
                            IngredientsId = 27,
                            ProductsId = 16
                        },
                        new
                        {
                            IngredientsId = 18,
                            ProductsId = 16
                        },
                        new
                        {
                            IngredientsId = 45,
                            ProductsId = 16
                        },
                        new
                        {
                            IngredientsId = 8,
                            ProductsId = 16
                        },
                        new
                        {
                            IngredientsId = 21,
                            ProductsId = 16
                        },
                        new
                        {
                            IngredientsId = 46,
                            ProductsId = 16
                        },
                        new
                        {
                            IngredientsId = 47,
                            ProductsId = 16
                        },
                        new
                        {
                            IngredientsId = 48,
                            ProductsId = 17
                        },
                        new
                        {
                            IngredientsId = 49,
                            ProductsId = 17
                        },
                        new
                        {
                            IngredientsId = 23,
                            ProductsId = 17
                        },
                        new
                        {
                            IngredientsId = 18,
                            ProductsId = 17
                        },
                        new
                        {
                            IngredientsId = 8,
                            ProductsId = 17
                        },
                        new
                        {
                            IngredientsId = 46,
                            ProductsId = 17
                        },
                        new
                        {
                            IngredientsId = 50,
                            ProductsId = 18
                        },
                        new
                        {
                            IngredientsId = 51,
                            ProductsId = 18
                        },
                        new
                        {
                            IngredientsId = 45,
                            ProductsId = 18
                        },
                        new
                        {
                            IngredientsId = 4,
                            ProductsId = 18
                        },
                        new
                        {
                            IngredientsId = 15,
                            ProductsId = 18
                        },
                        new
                        {
                            IngredientsId = 8,
                            ProductsId = 18
                        },
                        new
                        {
                            IngredientsId = 46,
                            ProductsId = 18
                        },
                        new
                        {
                            IngredientsId = 52,
                            ProductsId = 19
                        },
                        new
                        {
                            IngredientsId = 53,
                            ProductsId = 19
                        },
                        new
                        {
                            IngredientsId = 54,
                            ProductsId = 19
                        },
                        new
                        {
                            IngredientsId = 46,
                            ProductsId = 19
                        },
                        new
                        {
                            IngredientsId = 8,
                            ProductsId = 19
                        },
                        new
                        {
                            IngredientsId = 45,
                            ProductsId = 19
                        },
                        new
                        {
                            IngredientsId = 21,
                            ProductsId = 19
                        },
                        new
                        {
                            IngredientsId = 27,
                            ProductsId = 20
                        },
                        new
                        {
                            IngredientsId = 54,
                            ProductsId = 20
                        },
                        new
                        {
                            IngredientsId = 51,
                            ProductsId = 20
                        },
                        new
                        {
                            IngredientsId = 46,
                            ProductsId = 20
                        },
                        new
                        {
                            IngredientsId = 50,
                            ProductsId = 21
                        },
                        new
                        {
                            IngredientsId = 55,
                            ProductsId = 21
                        },
                        new
                        {
                            IngredientsId = 20,
                            ProductsId = 21
                        },
                        new
                        {
                            IngredientsId = 19,
                            ProductsId = 21
                        },
                        new
                        {
                            IngredientsId = 27,
                            ProductsId = 22
                        },
                        new
                        {
                            IngredientsId = 56,
                            ProductsId = 22
                        },
                        new
                        {
                            IngredientsId = 45,
                            ProductsId = 22
                        },
                        new
                        {
                            IngredientsId = 4,
                            ProductsId = 22
                        },
                        new
                        {
                            IngredientsId = 46,
                            ProductsId = 22
                        },
                        new
                        {
                            IngredientsId = 57,
                            ProductsId = 22
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sushi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "WOK"
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "salyami"
                        },
                        new
                        {
                            Id = 2,
                            Name = "mozzarella"
                        },
                        new
                        {
                            Id = 3,
                            Name = "tomato sauce"
                        },
                        new
                        {
                            Id = 4,
                            Name = "champignons"
                        },
                        new
                        {
                            Id = 5,
                            Name = "oregano"
                        },
                        new
                        {
                            Id = 6,
                            Name = "tabasco"
                        },
                        new
                        {
                            Id = 7,
                            Name = "italian sousages"
                        },
                        new
                        {
                            Id = 8,
                            Name = "onion"
                        },
                        new
                        {
                            Id = 9,
                            Name = "bavarian sausages"
                        },
                        new
                        {
                            Id = 10,
                            Name = "alfredo sause"
                        },
                        new
                        {
                            Id = 11,
                            Name = "dor blue"
                        },
                        new
                        {
                            Id = 12,
                            Name = "parmezan"
                        },
                        new
                        {
                            Id = 13,
                            Name = "cheddar"
                        },
                        new
                        {
                            Id = 14,
                            Name = "olives"
                        },
                        new
                        {
                            Id = 15,
                            Name = "tomatoes"
                        },
                        new
                        {
                            Id = 16,
                            Name = "basil"
                        },
                        new
                        {
                            Id = 17,
                            Name = "olive oil"
                        },
                        new
                        {
                            Id = 18,
                            Name = "chiken"
                        },
                        new
                        {
                            Id = 19,
                            Name = "pineapple"
                        },
                        new
                        {
                            Id = 20,
                            Name = "corn"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bualgaeian papper"
                        },
                        new
                        {
                            Id = 22,
                            Name = "black eyed peas"
                        },
                        new
                        {
                            Id = 23,
                            Name = "beacon"
                        },
                        new
                        {
                            Id = 24,
                            Name = "charries"
                        },
                        new
                        {
                            Id = 25,
                            Name = "salad iceberg"
                        },
                        new
                        {
                            Id = 26,
                            Name = "quail eggs"
                        },
                        new
                        {
                            Id = 27,
                            Name = "rice"
                        },
                        new
                        {
                            Id = 28,
                            Name = "nori"
                        },
                        new
                        {
                            Id = 29,
                            Name = "tuna"
                        },
                        new
                        {
                            Id = 30,
                            Name = "philadelphia cheese"
                        },
                        new
                        {
                            Id = 31,
                            Name = "cucumber"
                        },
                        new
                        {
                            Id = 32,
                            Name = "chili pepper"
                        },
                        new
                        {
                            Id = 33,
                            Name = "salmon"
                        },
                        new
                        {
                            Id = 34,
                            Name = "mango"
                        },
                        new
                        {
                            Id = 35,
                            Name = "tiger shrimp"
                        },
                        new
                        {
                            Id = 36,
                            Name = "microgeen"
                        },
                        new
                        {
                            Id = 37,
                            Name = "tobiko caviar"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Japanese mayonnaise"
                        },
                        new
                        {
                            Id = 39,
                            Name = "avocado"
                        },
                        new
                        {
                            Id = 40,
                            Name = "scrambled eggs"
                        },
                        new
                        {
                            Id = 41,
                            Name = "snow crab"
                        },
                        new
                        {
                            Id = 42,
                            Name = "tobika"
                        },
                        new
                        {
                            Id = 43,
                            Name = "unagi sauce"
                        },
                        new
                        {
                            Id = 44,
                            Name = "eel"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Chinese cabbage"
                        },
                        new
                        {
                            Id = 46,
                            Name = "carrot"
                        },
                        new
                        {
                            Id = 47,
                            Name = "sesame"
                        },
                        new
                        {
                            Id = 48,
                            Name = "udon"
                        },
                        new
                        {
                            Id = 49,
                            Name = "soy sauce"
                        },
                        new
                        {
                            Id = 50,
                            Name = "soba"
                        },
                        new
                        {
                            Id = 51,
                            Name = "brokolli"
                        },
                        new
                        {
                            Id = 52,
                            Name = "funchoza"
                        },
                        new
                        {
                            Id = 53,
                            Name = "mussels"
                        },
                        new
                        {
                            Id = 54,
                            Name = "shrimps"
                        },
                        new
                        {
                            Id = 55,
                            Name = "turkey"
                        },
                        new
                        {
                            Id = 56,
                            Name = "veal"
                        },
                        new
                        {
                            Id = 57,
                            Name = "peanut"
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = true,
                            TotalSum = 100m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false,
                            TotalSum = 200m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = true,
                            TotalSum = 300m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false,
                            TotalSum = 300m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 4,
                            ProductId = 4,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Cost = 205m,
                            Name = "Papperoni",
                            Weight = 450
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Cost = 215m,
                            Name = "Diablo",
                            Weight = 500
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Cost = 250m,
                            Name = "Four cheese",
                            Weight = 450
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Cost = 220m,
                            Name = "Salyami",
                            Weight = 550
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Cost = 200m,
                            Name = "Margarita",
                            Weight = 500
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Cost = 230m,
                            Name = "Hawaiian",
                            Weight = 450
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Cost = 220m,
                            Name = "Vegeterian",
                            Weight = 490
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Cost = 250m,
                            Name = "Caesar",
                            Weight = 530
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Cost = 130m,
                            Name = "Tuna Tataki",
                            Weight = 250
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Cost = 270m,
                            Name = "Mango roll",
                            Weight = 215
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Cost = 260m,
                            Name = "California with salmon",
                            Weight = 220
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Cost = 140m,
                            Name = "Tokio roll",
                            Weight = 250
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Cost = 155m,
                            Name = "Spider roll",
                            Weight = 230
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Cost = 230m,
                            Name = "Kanada roll",
                            Weight = 240
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Cost = 105m,
                            Name = "Cheese roll",
                            Weight = 220
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Cost = 120m,
                            Name = "Rice with Chiken",
                            Weight = 400
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Cost = 125m,
                            Name = "Udon with beacon",
                            Weight = 400
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Cost = 105m,
                            Name = "Soba with vegetables",
                            Weight = 400
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Cost = 185m,
                            Name = "Funchoza seafood",
                            Weight = 400
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Cost = 175m,
                            Name = "Rice with shrimps",
                            Weight = 400
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Cost = 145m,
                            Name = "Soba with turkey",
                            Weight = 400
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Cost = 125m,
                            Name = "Rice with veal",
                            Weight = 400
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin@restaurant.com",
                            Password = "$2a$12$ie9R50Trbh8G0AMkqmGi7eR8EpgKJXSrekpeUs3VwOPTASNotdsTe",
                            PhoneNumber = "0677678634",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Login = "user@test.com",
                            Password = "$2a$12$QLyrnlYxql6mShPy/Y.4hODTslCkM008Kc3ZYOq4bmGxWX7.2FNuq",
                            PhoneNumber = "0676512534",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("IngredientProduct", b =>
                {
                    b.HasOne("Restaurant.DAL.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.DAL.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Order", b =>
                {
                    b.HasOne("Restaurant.DAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.OrderDetail", b =>
                {
                    b.HasOne("Restaurant.DAL.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Product", b =>
                {
                    b.HasOne("Restaurant.DAL.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.User", b =>
                {
                    b.HasOne("Restaurant.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
